apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: save2win-extension

build:
  # NOTE: In v4, DO NOT put defaultRepo here (it causes the error you saw).
  # Pass --default-repo on the CLI instead.
  tagPolicy:
    gitCommit: {}
  platforms:
    - linux/amd64
  artifacts:
    # ---------- Next.js frontend ----------
    - image: save2win-frontend
      context: src/frontend
      docker:
        dockerfile: Dockerfile.frontend
      sync:
        manual:
          # paths are RELATIVE to context (src/frontend)
          - src: "app/**/*"
            dest: /app/app
          - src: "public/**/*"
            dest: /app/public

    # ---------- Game engine ----------
    - image: save2win-engine
      context: src/save2win-engine
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.py"
            dest: /app

    # ---------- MCP service ----------
    - image: mcp-service
      context: src/mcp
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.py"
            dest: /app

manifests:
  rawYaml:
    - kubernetes-manifests/*.yaml

deploy:
  kubectl:
    defaultNamespace: boa
  statusCheckDeadlineSeconds: 600

portForward:
  - resourceType: service
    resourceName: save2win-frontend
    namespace: boa
    port: 80
    localPort: 8080
  - resourceType: service
    resourceName: save2win-engine
    namespace: boa
    port: 80
    localPort: 8081
  - resourceType: service
    resourceName: mcp-service
    namespace: boa
    port: 80
    localPort: 8082

profiles:
  # Build/deploy with Google Cloud Build, but ONLY the frontend artifact.
  # This avoids the "FROM builder/deps" errors in engine/MCP until those Dockerfiles are fixed.
  - name: gcb-frontend
    build:
      googleCloudBuild:
        projectId: gke-trial-472609
      artifacts:
        - image: save2win-frontend
          context: src/frontend
          docker:
            dockerfile: Dockerfile
          sync:
            manual:
              - src: "app/**/*"
                dest: /app/app
              - src: "public/**/*"
                dest: /app/public
    manifests:
      rawYaml:
        - kubernetes-manifests/*save2win-frontend*.yaml
        - kubernetes-manifests/ingress.yaml
        - kubernetes-manifests/oauth-config.yaml

  # Full build (all artifacts) via GCB — use this once engine/MCP Dockerfiles are fixed.
  - name: gcb-all
    build:
      googleCloudBuild:
        projectId: gke-trial-472609

  # Local dev (no push) — handy for minikube/kind
  - name: dev
    build:
      local:
        push: false

  # Prod tagging style (optional)
  - name: prod
    build:
      tagPolicy:
        sha256: {}
