# kubernetes-manifests/backend-config.yaml
#
# Defines a custom health check for the GKE load balancer.
# This is critical for ensuring traffic is only sent to healthy pods.

apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: save2win-backend-config
  namespace: boa
spec:
  healthCheck:
    type: HTTP
    requestPath: /healthz
    port: 3000
    checkIntervalSec: 15
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 3