# ==============================================================================
#  1. Kubernetes Service Account (KSA)
# ==============================================================================
apiVersion: v1
kind: ServiceAccount
metadata:
  name: save2win-engine-sa
  namespace: boa
---
# ==============================================================================
#  2. Deployment
# ==============================================================================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: save2win-engine
  namespace: boa
  labels:
    app: save2win-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: save2win-engine
  template:
    metadata:
      labels:
        app: save2win-engine
    spec:
      serviceAccountName: save2win-engine-sa
      containers:
        - name: server
          image: save2win-engine
          ports:
            - containerPort: 8080
          # --- FIX FOR AUTOPILOT ---
          # These values meet Autopilot's minimum requirements for general-purpose workloads.
          resources:
            requests:
              cpu: "250m"      # 0.25 vCPU
              memory: "512Mi" # 512 MB of RAM
---
# ==============================================================================
#  3. Service
# ==============================================================================
apiVersion: v1
kind: Service
metadata:
  name: save2win-engine
  namespace: boa
  labels:
    app: save2win-engine
spec:
  type: ClusterIP
  selector:
    app: save2win-engine
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080