apiVersion: v1
kind: ServiceAccount
metadata:
  name: save2win-engine-sa
  namespace: boa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: save2win-engine
  namespace: boa
  labels:
    app: save2win-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: save2win-engine
  template:
    metadata:
      labels:
        app: save2win-engine
    spec:
      serviceAccountName: save2win-engine-sa
      containers:
        - name: server
          image: save2win-engine
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: public-key-volume
              mountPath: /var/private/
              readOnly: true
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
      volumes:
        - name: public-key-volume
          secret:
            secretName: public-key
            items:
            - key: key.pub
              path: boa_jwt_key.pub
---
apiVersion: v1
kind: Service
metadata:
  name: save2win-engine
  namespace: boa
  labels:
    app: save2win-engine
spec:
  type: ClusterIP
  selector:
    app: save2win-engine
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080