apiVersion: apps/v1
kind: Deployment
metadata:
  name: save2win-engine
  namespace: boa
  labels:
    app: save2win-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: save2win-engine
  template:
    metadata:
      labels:
        app: save2win-engine
    spec:
      serviceAccountName: save2win-engine-sa
      containers:
        - name: server
          image: save2win-engine
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: engine-jwt
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
